name: LocalChat
version: '1.0-SNAPSHOT'
main: org.LegendaryHardcore.localChat.LocalChat
api-version: '1.21'

commands:
  l:
    description: Sends a message only to nearby players.
    usage: /l <message>
    aliases: [local]
  localtoggle:
    description: Toggles local chat
    usage: /localtoggle